version: 0.2

# Expected environment variables from CodePipeline:
# BRANCH (e.g. master, dev, staging)
# COUNTRY (e.g. mx, do, ec)
# REGION (e.g. us-west-2, sa-east-1)

env:
  variables:
    SSM_REGION: us-west-2 # Parameter store linking country-branch to account, build role
    HANDLER_FILE: src/serverless-api.js
phases:
  install:
    commands:
      - if [[ -z "${BRANCH}" || -z "${COUNTRY}" || -z "${REGION}" ]]; then exit 99; fi
      - env
      - sed -i "s/%%COUNTRY%%/${COUNTRY}/g" $HANDLER_FILE
      - sed -i "s/%%BRANCH%%/${BRANCH}/g" $HANDLER_FILE
      - sed -i "s/%%BUILDDATE%%/`date`/g" $HANDLER_FILE
      - npm install
      - npm install -g serverless
  pre_build:
    commands:
      - assumeRole=$(aws ssm get-parameter --with-decryption --name "/deploy/${COUNTRY}-${BRANCH}" --region $SSM_REGION | jq '.Parameter.Value' | jq -r '.|fromjson | .buildRole')
      - assumeCreds=$(aws sts assume-role --role-arn "${assumeRole}" --role-session-name "CodeDeploy_Master_${COUNTRY}")
      - echo "Deploying ${BRANCH} to ${COUNTRY} in ${REGION} using ${assumeRole}"
      - export AWS_ACCESS_KEY_ID=$(jq -r .Credentials.AccessKeyId <<< "$assumeCreds")
      - export AWS_SECRET_ACCESS_KEY=$(jq -r .Credentials.SecretAccessKey <<< "$assumeCreds")
      - export AWS_SESSION_TOKEN=$(jq -r .Credentials.SessionToken <<< "$assumeCreds")
  build:
    commands:
      - serverless deploy --verbose --stage $BRANCH --region $REGION
  #post_build:
    #commands:
      # - command
      # - command